### ISSUE TITLE
[Bug]无法解析b23.tv短链

### ISSUE THREAD

**Issue by 050644zf** [mengshouer/nonebot_plugin_analysis_bilibili#15]
解析BV号AV号链接正常，解析b23.tv短链出现以下报错：
```
04-15 13:13:44 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_analysis_bilibili) failed.
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 1067, in create_connection
    raise exceptions[0]
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 1052, in create_connection
    sock = await self._connect_sock(
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 963, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\proactor_events.py", line 705, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\bot\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\Anaconda3\envs\bot\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\envs\bot\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "D:\ProgramData\Anaconda3\envs\bot\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot_plugin_analysis_bilibili\__init__.py", line 23, in analysis_main
    text = await b23_extract(text)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\nonebot_plugin_analysis_bilibili\analysis_bilibili.py", line 58, in b23_extract
    async with aiohttp.request("GET", url) as resp:
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\client.py", line 1189, in __aenter__
    self._resp = await self._coro
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\ProgramData\Anaconda3\envs\bot\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host b23.tv:443 ssl:default [信号灯超时时间已到]
```

**Comment by mengshouer** [comment]
我这里测试没问题，合理怀疑的网络环境问题(
