### ISSUE TITLE
[bug]无法响应群信息。

### ISSUE THREAD

**Issue by sherlockHlb** [mengshouer/nonebot_plugin_analysis_bilibili#17]
版本:最新版本
cq:1.0.1

出现错误操作:群里发链接解析直接报错

错误内容：05-23 10:33:53 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_analysis_bilibili) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_analysis_bilibili\__init__.py", line 35, in analysis_main
    await analysis_bili.send(msg)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 466, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_guild_patch\__init__.py", line 30, in patched_send
    return await original_send(self, event, message, **kwargs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 174, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 140, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='6', message='send group message failed: blocked by server', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='send group message failed: blocked by server')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\bot.py", line 17, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1919, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_analysis_bilibili\__init__.py", line 39, in analysis_main
    msg = re.sub(r"简介.*", "", msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object, got 'Message'

**Comment by mengshouer** [comment]
更新到最新版再提bug
