### ISSUE TITLE
使用RedProtocol连接nb2的环境下插件发送信息时出错

### ISSUE THREAD

**Issue by twfx1207** [mengshouer/nonebot_plugin_analysis_bilibili#21]
报错信息：
```
11-23 12:08:31 [ERROR] nonebot_plugin_analysis_bilibili | 'MessageSegment' object has no attribute 'upload'
Traceback (most recent call last):
  File "<string>", line 33, in <module>
  File "/usr/local/lib/python3.11/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.11/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "/usr/local/lib/python3.11/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/usr/local/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.11/site-packages/nonebot_plugin_analysis_bilibili/__init__.py", line 138, in handle_analysis
    await send_msg(msg)
  File "/usr/local/lib/python3.11/site-packages/nonebot_plugin_analysis_bilibili/__init__.py", line 97, in send_msg
    await analysis_bili.send(format_msg(msg_list))
  File "/usr/local/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 554, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/nonebot/adapters/red/bot.py", line 238, in send
    element_data = await message.export(self)
  File "/usr/local/lib/python3.11/site-packages/nonebot/adapters/red/message.py", line 389, in export
    resp = await seg.upload(bot)
AttributeError: 'MessageSegment' object has no attribute 'upload'
```

**Comment by mengshouer** [comment]
chronocat 寄了，没有使用过，没有测试环境，而且代码中 MessageSegment 没有调用过 upload 函数，猜测是 red 适配器的问题(

**Comment by twfx1207** [comment]
昨天尝试用red的MessageSegment重载了一遍还是出错，研究了一下，red连接器不能直接用url方式发图片，需要先把图片下载下来再传路径给连接器。

**Comment by mengshouer** [comment]
你python依赖包里面还有onebot11的适配器吗，不是onebot11的话根本不会发送图片，只有文字。

**Comment by twfx1207** [comment]
> 你python依赖包里面还有onebot11的适配器吗，不是onebot11的话根本不会发送图片，只有文字。

onebot11适配器还在项目中，但是激活的适配器只有red了。
最简单的方法应该是用saa的MessageSegmentFactory抽象类把MessageSegment的构建部分重写一遍，这样也不需要单独对其他适配器做处理了。晚上研究一下
