### ISSUE TITLE
搜视频的api用不了了

### ISSUE THREAD

**Issue by Zhalslar** [mengshouer/nonebot_plugin_analysis_bilibili#30]
使用搜视频指令时出现这个问题：
12-03 18:10:07 [SUCCESS] nonebot | OneBot V11 536914282 | [message.group.normal]: Message 596030558 from 2936169201@[群:1042943832] '搜视频 无限暖暖'
12-03 18:10:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_analysis_bilibili, lineno=83)
12-03 18:10:08 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_analysis_bilibili, lineno=83) running complete
12-03 18:10:08 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_analysis_bilibili, lineno=83) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 337, in run
    get_driver().run(*args, **kwargs)
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 188, in run
    uvicorn.run(
  File "/root/test2/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/test2/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/utils.py", line 254, in run_coro_with_shield
    return await coro
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/message.py", line 506, in check_and_run_matcher
    await _run_matcher(
> File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/message.py", line 458, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 900, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 837, in simple_run
    await handler(
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot_plugin_analysis_bilibili/__init__.py", line 191, in handle_search
    msg = await get_msg(event, str(event.get_message())[3:].strip(), search=True)
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot_plugin_analysis_bilibili/__init__.py", line 152, in get_msg
    text = await search_bili_by_title(text, session=session)
  File "/root/test2/.venv/lib/python3.10/site-packages/nonebot_plugin_analysis_bilibili/analysis_bilibili.py", line 154, in search_bili_by_title
    for i in result["data"]["result"]:
KeyError: 'result'

**Comment by mengshouer** [comment]
更新 2.8.1 看看
